print('Qual o formato primitivo da variavel?')
variavel = input('Digite um valor para a variavel:')
print('O tipo primitivo é', type(variavel))
print('é alphanumerico?', variavel.isalnum())
print('é alphabetica?', variavel.isalpha())
print('é ascii?', variavel.isascii())
print('é decimal?', variavel.isdecimal())
print('é um digito?', variavel.isdigit())
print('é um identificador?', variavel.isidentifier())
print('está completamente em minuscula?', variavel.islower())
print('é um numero?', variavel.isnumeric())
print('é printavel?', variavel.isprintable())
print('é um espaço?', variavel.isspace())
print('é um titulo?', variavel.istitle())
print('está completamente em maiuscula?', variavel.isupper())
